config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    member do
      get :follow
      get :unfollow
    end
  end

  match "/posts/new_comment" => "posts#new_comment", :as => "new_comment_to_posts", :via => [:post]

  resources :comments

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#homepage'
  get 'welcome/events'

  devise_scope :user do
    delete "/users/logout" => "devise/sessions#destroy"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :find_commentable, only: :create
  respond_to :js

  def create
    @comment = @commentable.comments.new do |comment|
      comment.comment = params[:comment_text]
      comment.user = current_user
    end
    @comment.save
    #redirect_to :back
    respond_to do |format|
    format.js {render inline: "location.reload();" }
end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment_id = params[:id]
    @comment.destroy
    redirect_to :back
  end

  private
  def find_commentable
    @commentable_type = params[:commentable_type].classify
    @commentable = @commentable_type.constantize.find(params[:commentable_id])
  end

  def set_user
    @user = current_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @post.comments.each do |comment| %>
  <span id="<%= comment.id %>">
    
    <h5>Posted on: <%= comment.created_at.to_time.strftime("%b %d, %Y on %I:%M %p") %>
    <p> By: <%= comment.user.first_name %> </p>
    </h5>

    <p> <%= comment.comment %> </p>
    
  </span>
<% end %>

app/views/comments/_form.html.erb
<%= form_tag comments_path(commentable_type: commentable.class.to_s, commentable_id: commentable.id), method: :post, remote: true do %>
    <div class="form-group">
      <%= text_area_tag :comment_text, nil, placeholder: 'Enter Comment', class: 'form-control' %>
    </div>
    <%= submit_tag :comment, class: 'btn btn-primary' %>
    
<% end %>

app/views/comments/create.js.erb
$("#<%= @commentable_type.downcase %>-<%= @commentable.id %> .comments").prepend("<%=j render(@comment) %>");
$("#comment_text").val("");

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();