config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    member do
      get :follow
      get :unfollow
    end
  end

  match "/posts/new_comment" => "posts#new_comment", :as => "new_comment_to_posts", :via => [:post]

  resources :comments

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#homepage'
  get 'welcome/events'

  devise_scope :user do
    delete "/users/logout" => "devise/sessions#destroy"
  end

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_post
  respond_to :js

  def create
    @post = Post.find(params[:post_id])
    current_user.follow(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    current_user.stop_following(@post)
  end

  private
  def set_user
    @user = current_user
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_form.html.erb
<div class="follow">
  <% if @post.followed_by?(@user) %>
      <%= form_tag unfollow_post_path(post_id: @post), method: :post, remote: true do %>
          <%= link_to "BackOut", unfollow_post_path, class: "btn btn-default" %>
      <% end %>
  <% else %>
      <%= form_tag follow_post_path(post_id: @post), method: :post, remote: true do %>
          <%= link_to "JoinIn", follow_post_path, class: "btn btn-default" %>
      <% end %>
  <% end %>
</div>

app/views/follows/create.js.erb
$("#post-<%= @post.id %> .follow").html("<%=j render('follows/form', post: @post) %>");

app/views/follows/destroy.js.erb
$("#post-<%= @post.id %> .follow").html("<%=j render('follows/form', post: @post) %>");