config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    member do
      get :follow
      get :unfollow
    end
  end

  match "/posts/new_comment" => "posts#new_comment", :as => "new_comment_to_posts", :via => [:post]

  resources :comments

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#homepage'
  get 'welcome/events'

  devise_scope :user do
    delete "/users/logout" => "devise/sessions#destroy"
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  has_many :comments
  acts_as_followable
  acts_as_commentable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new', notice: @post.errors.full_messages.first
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def follow
    @post = Post.find(params[:id])

    if current_user
      current_user.follow(@post)
      redirect_to :back, :notice => "You successfully joined into an event!"
    else
      redirect_to :back, :notice => "You must <a href='/users/sign_in'>login</a> to follow that post."
    end
  end

  def unfollow
    @post = Post.find(params[:id])

    if current_user
        current_user.stop_following(@post)
        redirect_to :back, :notice => "You successfully backed out of an event"
    else
      redirect_to :back, :notice => "You must <a href='/users/sign_in'>login</a> to follow that post."
    end
  end

  def new_comment
    @post = Post.find(params[:id])
    @post.comments << Post.new(comment_params)
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit!
  end

  def post_params
    params.require(:post).permit(:title, :address, :start_time, :end_time, :body)
  end

  def set_user
    @user = current_user
  end

  def end_must_be_after_start
    if :start_time >= :end_time
      errors.add(:end_time, "must be after start time")
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
    <%= f.input :title, autofocus: true %>
    <%= f.input :address %>
    <%= f.input :start_time, as: :datetime %>
    <%= f.input :end_time, as: :datetime %>
    <%= f.text_area :body, class: 'form-control',
                    placeholder: 'Event description' %>
    <%= f.submit :post, class: 'btn btn-primary'%>
<% end %>
<%= link_to "Back", posts_path, class: "btn btn-default" %>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12 text-center">
  			<h2 class="section-heading">Event Listings</h2>
    </div>
  </div>
  <%= link_to 'Create Event', new_post_path, class: "btn btn-success" %>
  <%= link_to 'Your Listings', welcome_events_path , class: "btn btn-success" %>
<div class="row text-center">
  <% @posts.each do |post| %>
     <div class="col-md-4">
       <span class="fa-stack fa-4x">
           <i class="fa fa-circle fa-stack-2x text-primary"></i>
           <i class="fa fa-user fa-stack-1x fa-inverse"></i>
      </span>
    <h4 class="service-heading"><%= post.title %> </h4>
    <p class="text-muted"> <%= post.address %> </p>
    <p class="text-muted"> <%= post.body %> </p>
    <%= link_to 'More Details', post %>
    </div>
  <% end %>
</div>
</div>

app/views/posts/new.html.erb
<h1>Create Event</h1>

<%=render partial: 'form' %>

app/views/posts/show.html.erb
<div class="container" data-no-turbolink="true">



<div class="page-header">
<h1><%= @post.title %></h1>
</div>
  <p class="text-muted"> <%= @post.address %> </p>
  <p class="text-muted"> Start Time : <%= @post.start_time.to_time.strftime("%b %d, %Y on %I:%M %p")  %></p>
  <p class="text-muted"> End Time : <%= @post.end_time.to_time.strftime("%b %d, %Y on %I:%M %p") %></p>
  <p class="text-muted"> <%= @post.body %> </p>

  <h4> Comments</h4>


  <%= render :partial => 'comments/comment', :locals => {:post => @post} %>
  <%= render :partial => 'comments/form', :locals => {:commentable => @post} %>

  <%= render :partial => 'follows/form', :locals => {:followable => @post} %>
	<%= link_to "Back", posts_path, class: "btn btn-default" %>

</div>